# Generated by Django 5.2.17 on 2026-09-05 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espn", "0002_injury_newsarticle_transaction_athleteseasonstats"),
    ]

    operations = [
        migrations.CreateModel(
            name="Odds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider_espn_id", models.CharField(db_index=True, max_length=50)),
                ("provider_name", models.CharField(blank=True, max_length=100)),
                ("market", models.CharField(db_index=True, max_length=30)),
                ("selection", models.CharField(max_length=30)),
                ("line", models.CharField(blank=True, default="", max_length=10)),
                ("decimal_odds", models.FloatField()),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odds",
                        to="espn.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Odds",
                "verbose_name_plural": "Odds",
                "ordering": ["event", "market", "selection"],
                "unique_together": {
                    ("event", "provider_espn_id", "market", "selection", "line")
                },
            },
        ),
    ]
