# Generated by Django 5.2.17 on 2026-09-07 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espn", "0003_odds"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpectedGoals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "home",
                    models.FloatField(help_text="Expected goals for the home side."),
                ),
                (
                    "away",
                    models.FloatField(help_text="Expected goals for the away side."),
                ),
                ("home_shots", models.PositiveIntegerField(default=0)),
                ("away_shots", models.PositiveIntegerField(default=0)),
                (
                    "source",
                    models.CharField(db_index=True, default="understat", max_length=40),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expected_goals",
                        to="espn.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expected goals",
                "verbose_name_plural": "Expected goals",
            },
        ),
    ]
