"""Walk-forward backtest of the scoreline model.

For every match in the window the model is refitted on matches that finished
strictly before it, so no result ever informs its own prediction. Two questions
are answered separately:

1. Is the model well calibrated? Log-loss, Brier score and a calibration table
   answer this, and both are reported next to a base-rate baseline — a log-loss
   is meaningless on its own, only in comparison to a naive predictor.
2. Would betting on it have made money? Only answerable where real odds are
   stored, and only ever about the past.

A backtest run on seeded demo data measures nothing about profitability: the
results were generated by a random process the model can partly recover, with
synthetic prices. Treat the betting section as a check that the machinery works.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from datetime import datetime

from apps.espn import club_elo, elo, markets
from apps.espn.analysis import _completed_events, _sided_competitors
from apps.espn.dixon_coles import (
    DEFAULT_HALF_LIFE_DAYS,
    RELIABLE_MATCH_COUNT,
    ModelFit,
    NotEnoughData,
    fit,
    score_grid,
)
from apps.espn.forecast import MINIMUM_MATCHES, collect_observations
from apps.espn.models import League, Odds
from apps.espn.value import (
    DEFAULT_EDGE_THRESHOLD,
    DEFAULT_KELLY_FRACTION,
    DEFAULT_MAX_STAKE_FRACTION,
    PricedSelection,
    find_value_bets,
    remove_margin,
)

OUTCOMES = (markets.SELECTION_HOME, markets.SELECTION_DRAW, markets.SELECTION_AWAY)
CALIBRATION_BINS = 10
_LOG_FLOOR = 1e-15


def outcome_of(home_goals: int, away_goals: int) -> str:
    if home_goals > away_goals:
        return markets.SELECTION_HOME
    if home_goals < away_goals:
        return markets.SELECTION_AWAY
    return markets.SELECTION_DRAW


def settle(market: str, selection: str, line: str, home_goals: int, away_goals: int) -> bool | None:
    """Did this selection win? None when the market is not understood."""
    if market == markets.MARKET_MATCH_ODDS:
        return outcome_of(home_goals, away_goals) == selection

    if market == markets.MARKET_TOTALS:
        try:
            threshold = float(line)
        except (TypeError, ValueError):
            return None
        total = home_goals + away_goals
        if selection == "over":
            return total > threshold
        if selection == "under":
            return total < threshold
        return None

    if market == markets.MARKET_BTTS:
        both = home_goals > 0 and away_goals > 0
        if selection == "yes":
            return both
        if selection == "no":
            return not both
        return None

    if market == markets.MARKET_DOUBLE_CHANCE:
        result = outcome_of(home_goals, away_goals)
        mapping = {
            "home_or_draw": {markets.SELECTION_HOME, markets.SELECTION_DRAW},
            "home_or_away": {markets.SELECTION_HOME, markets.SELECTION_AWAY},
            "draw_or_away": {markets.SELECTION_DRAW, markets.SELECTION_AWAY},
        }
        return result in mapping[selection] if selection in mapping else None

    return None


@dataclass
class ForecastRecord:
    """One out-of-sample prediction and what actually happened."""

    event_espn_id: str
    date: datetime
    home: str
    away: str
    probabilities: dict[str, float]
    actual: str
    home_goals: int
    away_goals: int
    # The market's own devigged opinion on the same fixture, when odds are stored.
    market_probabilities: dict[str, float] | None = None
    # An independent second model, so the two can be compared and combined.
    elo_probabilities: dict[str, float] | None = None
    # A third, rated over every competition its clubs play rather than only this
    # league — the only one that knows anything about a promoted side.
    club_elo_probabilities: dict[str, float] | None = None
    # What the market settled on. Not a price anybody could have taken when this
    # forecast was made — it exists only to score the forecast against, never to
    # bet into.
    closing_probabilities: dict[str, float] | None = None
    # The decimal odds behind both, kept because closing-line value is a question
    # about prices rather than probabilities.
    opening_prices: dict[str, float] | None = None
    closing_prices: dict[str, float] | None = None


@dataclass
class BettingLedger:
    """Bankroll simulation over the settled value bets."""

    starting_bankroll: float = 1.0
    bankroll: float = 1.0
    peak: float = 1.0
    max_drawdown: float = 0.0
    staked: float = 0.0
    returned: float = 0.0
    bets: int = 0
    wins: int = 0
    # Profit per unit staked for each bet, used to put an error bar on the yield.
    flat_returns: list[float] = field(default_factory=list)

    def record(self, stake_fraction: float, decimal_odds: float, won: bool) -> None:
        stake = stake_fraction * self.bankroll
        if stake <= 0:
            return
        self.bets += 1
        self.staked += stake
        self.flat_returns.append(decimal_odds - 1.0 if won else -1.0)
        if won:
            self.wins += 1
            self.returned += stake * decimal_odds
            self.bankroll += stake * (decimal_odds - 1.0)
        else:
            self.bankroll -= stake

        self.peak = max(self.peak, self.bankroll)
        if self.peak > 0:
            self.max_drawdown = max(self.max_drawdown, (self.peak - self.bankroll) / self.peak)

    def to_dict(self) -> dict:
        profit = self.returned - self.staked
        flat_yield, stderr, t_stat = self._flat_yield_statistics()
        return {
            "bets": self.bets,
            "wins": self.wins,
            "hit_rate": round(self.wins / self.bets, 4) if self.bets else None,
            "staked": round(self.staked, 4),
            "profit": round(profit, 4),
            "yield": round(profit / self.staked, 4) if self.staked else None,
            "flat_stake_yield": flat_yield,
            # A yield within roughly two standard errors of zero is indistinguishable
            # from no edge, however large it looks.
            "flat_yield_stderr": stderr,
            "flat_yield_t_stat": t_stat,
            "distinguishable_from_zero": (
                bool(t_stat is not None and abs(t_stat) >= 2.0) if self.bets else None
            ),
            "final_bankroll": round(self.bankroll, 4),
            "growth": round(self.bankroll / self.starting_bankroll - 1.0, 4),
            "max_drawdown": round(self.max_drawdown, 4),
        }

    def _flat_yield_statistics(self) -> tuple[float | None, float | None, float | None]:
        count = len(self.flat_returns)
        if count == 0:
            return None, None, None
        mean = sum(self.flat_returns) / count
        if count < 2:
            return round(mean, 4), None, None
        variance = sum((value - mean) ** 2 for value in self.flat_returns) / (count - 1)
        stderr = math.sqrt(variance / count)
        t_stat = mean / stderr if stderr > 0 else None
        return (
            round(mean, 4),
            round(stderr, 4),
            round(t_stat, 2) if t_stat is not None else None,
        )


@dataclass
class BacktestReport:
    league: str
    forecasts: list[ForecastRecord] = field(default_factory=list)
    ledger: BettingLedger = field(default_factory=BettingLedger)
    skipped_no_history: int = 0
    skipped_unknown_team: int = 0
    skipped_unreliable_fit: int = 0
    events_with_odds: int = 0
    refits: int = 0

    def to_dict(self) -> dict:
        return {
            "league": self.league,
            "forecasts": len(self.forecasts),
            "refits": self.refits,
            "skipped": {
                "insufficient_history": self.skipped_no_history,
                "team_not_in_model": self.skipped_unknown_team,
                "unreliable_fit_not_bet": self.skipped_unreliable_fit,
            },
            "accuracy": _accuracy(self.forecasts),
            "model": _scores(self.forecasts),
            "baseline": _baseline_scores(self.forecasts),
            "market": _market_comparison(self.forecasts),
            "calibration": _calibration(self.forecasts),
            "betting": {
                "events_with_odds": self.events_with_odds,
                **self.ledger.to_dict(),
            },
        }


def _accuracy(records: list[ForecastRecord]) -> float | None:
    if not records:
        return None
    hits = sum(
        1 for r in records if max(r.probabilities, key=lambda k: r.probabilities[k]) == r.actual
    )
    return round(hits / len(records), 4)


def _scores(
    records: list[ForecastRecord], source: str = "probabilities"
) -> dict[str, float | None]:
    """Log-loss and Brier for one set of probabilities over the given records."""
    usable = [record for record in records if getattr(record, source)]
    if not usable:
        return {"log_loss": None, "brier": None}
    log_loss = 0.0
    brier = 0.0
    for record in usable:
        probabilities = getattr(record, source)
        log_loss -= math.log(max(probabilities[record.actual], _LOG_FLOOR))
        for outcome in OUTCOMES:
            actual = 1.0 if outcome == record.actual else 0.0
            brier += (probabilities[outcome] - actual) ** 2
    return {
        "log_loss": round(log_loss / len(usable), 4),
        "brier": round(brier / len(usable), 4),
    }


def _baseline_scores(records: list[ForecastRecord]) -> dict[str, float | None]:
    """Reference scores for always predicting the window's outcome frequencies.

    These rates are measured on the same window they score, so the baseline is
    in-sample and flattered: the model losing to it is not damning, but clearly
    beating it is meaningful.
    """
    if not records:
        return {"log_loss": None, "brier": None, "rates": {}}
    rates = {
        outcome: sum(1 for r in records if r.actual == outcome) / len(records)
        for outcome in OUTCOMES
    }
    baseline = [
        ForecastRecord(
            event_espn_id=r.event_espn_id,
            date=r.date,
            home=r.home,
            away=r.away,
            probabilities=rates,
            actual=r.actual,
            home_goals=r.home_goals,
            away_goals=r.away_goals,
        )
        for r in records
    ]
    return {**_scores(baseline), "rates": {k: round(v, 4) for k, v in rates.items()}}


def _market_comparison(records: list[ForecastRecord]) -> dict:
    """Score the model against the bookmaker price on the fixtures both cover.

    This is the question that decides whether any of this is worth betting: not
    "does the model predict football well" but "does it know something the price
    does not". Both are scored on the same subset — comparing a model measured on
    every match against a market measured on the subset with odds would be
    meaningless.

    Beating the closing price consistently is rare and hard; a model that merely
    matches it has still learned the market's information, not beaten it.
    """
    paired = [record for record in records if record.market_probabilities]
    if not paired:
        return {"matches": 0, "model": None, "market": None}

    model = _scores(paired, "probabilities")
    market = _scores(paired, "market_probabilities")
    delta = (
        round(model["log_loss"] - market["log_loss"], 4)
        if model["log_loss"] is not None and market["log_loss"] is not None
        else None
    )
    return {
        "matches": len(paired),
        "model": model,
        "market": market,
        # Negative means the model carries information the price did not.
        "log_loss_delta": delta,
        "model_beats_market": bool(delta is not None and delta < 0),
        "market_calibration": _calibration(paired, "market_probabilities"),
    }


def _calibration(records: list[ForecastRecord], source: str = "probabilities") -> list[dict]:
    """Predicted vs observed frequency, over every outcome of every match."""
    buckets: list[dict] = [
        {
            "bucket": f"{index / CALIBRATION_BINS:.1f}-{(index + 1) / CALIBRATION_BINS:.1f}",
            "predictions": 0,
            "_predicted": 0.0,
            "_observed": 0,
        }
        for index in range(CALIBRATION_BINS)
    ]

    for record in records:
        probabilities = getattr(record, source)
        if not probabilities:
            continue
        for outcome in OUTCOMES:
            probability = probabilities[outcome]
            index = min(int(probability * CALIBRATION_BINS), CALIBRATION_BINS - 1)
            buckets[index]["predictions"] += 1
            buckets[index]["_predicted"] += probability
            buckets[index]["_observed"] += 1 if outcome == record.actual else 0

    result = []
    for bucket in buckets:
        count = bucket["predictions"]
        if not count:
            continue
        result.append(
            {
                "bucket": bucket["bucket"],
                "predictions": count,
                "mean_predicted": round(bucket["_predicted"] / count, 4),
                "observed": round(bucket["_observed"] / count, 4),
            }
        )
    return result


# Devigging a "best price across bookmakers" line is meaningless — its overround
# is near or below 1, so it would read as a permanent edge. A single book's own
# quote is a coherent market with a real margin, so that is what gets devigged.
# Pinnacle first where it is stored: its margin is roughly half Bet365's, which
# makes it the harder and more honest benchmark. Falls back to Bet365 on leagues
# loaded from a source that carries no Pinnacle prices.
MARKET_BENCHMARK_PROVIDERS = ("fd-ps", "fd-b365")
# The same two books, as the market settled rather than as it opened.
CLOSING_BENCHMARK_PROVIDERS = ("fd-psc", "fd-b365c")


def _complete_books(prices: list[PricedSelection]) -> dict[str, dict[str, float]]:
    """Every provider quoting all three outcomes of the 1X2 market."""
    by_provider: dict[str, dict[str, float]] = {}
    for price in prices:
        if price.market != markets.MARKET_MATCH_ODDS or price.line:
            continue
        by_provider.setdefault(price.provider_espn_id, {})[price.selection] = price.decimal_odds
    return {
        provider: quotes for provider, quotes in by_provider.items() if set(quotes) == set(OUTCOMES)
    }


def _book_prices(
    prices: list[PricedSelection],
    providers: tuple[str, ...],
    *,
    strict: bool = False,
) -> dict[str, float] | None:
    """The preferred provider's raw decimal odds for the three outcomes.

    ``strict`` refuses to fall back to an unlisted provider. Closing prices are
    read strictly: silently substituting a pre-match book for a closing one would
    turn the whole comparison into a tautology.
    """
    complete = _complete_books(prices)
    if not complete:
        return None
    provider = next((name for name in providers if name in complete), None)
    if provider is None:
        if strict:
            return None
        provider = next(iter(complete))
    return complete[provider]


def _devigged(book: dict[str, float] | None) -> dict[str, float] | None:
    if not book:
        return None
    fair = remove_margin(book)
    if set(fair) != set(OUTCOMES):
        return None
    return {outcome: fair[outcome] for outcome in OUTCOMES}


def _market_probabilities(prices: list[PricedSelection]) -> dict[str, float] | None:
    """Devig one provider's 1X2 prices into a probability the model can be scored against."""
    by_provider: dict[str, dict[str, float]] = {}
    for price in prices:
        if price.market != markets.MARKET_MATCH_ODDS or price.line:
            continue
        by_provider.setdefault(price.provider_espn_id, {})[price.selection] = price.decimal_odds

    complete = {
        provider: quotes for provider, quotes in by_provider.items() if set(quotes) == set(OUTCOMES)
    }
    if not complete:
        return None

    provider = next(
        (name for name in MARKET_BENCHMARK_PROVIDERS if name in complete),
        next(iter(complete)),
    )
    fair = remove_margin(complete[provider])
    if set(fair) != set(OUTCOMES):
        return None
    return {outcome: fair[outcome] for outcome in OUTCOMES}


def _priced_selections(event_id: int) -> list[PricedSelection]:
    return [
        PricedSelection(
            market=row.market,
            selection=row.selection,
            line=row.line,
            decimal_odds=row.decimal_odds,
            provider_espn_id=row.provider_espn_id,
            provider_name=row.provider_name,
        )
        for row in Odds.objects.filter(event_id=event_id)
    ]


def run(
    league: League,
    *,
    date_from: datetime | None = None,
    date_to: datetime | None = None,
    half_life_days: float = DEFAULT_HALF_LIFE_DAYS,
    refit_every: int = 1,
    edge_threshold: float = DEFAULT_EDGE_THRESHOLD,
    kelly_multiplier: float = DEFAULT_KELLY_FRACTION,
    max_stake_fraction: float = DEFAULT_MAX_STAKE_FRACTION,
    starting_bankroll: float = 1.0,
    min_effective_matches: float = RELIABLE_MATCH_COUNT,
    elo_config: elo.EloConfig | None = None,
) -> BacktestReport:
    """Replay a league's history, predicting each match from only its past.

    Forecasts are recorded for every match with enough history to fit at all, but
    bets are only placed once the fit carries ``min_effective_matches`` worth of
    weighted history — early-season ratings swing enough to manufacture edges
    that are really just estimation noise.
    """
    report = BacktestReport(league=league.slug)
    report.ledger = BettingLedger(starting_bankroll=starting_bankroll, bankroll=starting_bankroll)

    events = list(_completed_events(league).order_by("date"))
    if date_from:
        events = [event for event in events if event.date >= date_from]
    if date_to:
        events = [event for event in events if event.date <= date_to]

    # The league's whole history is read once and sliced in memory as the replay
    # advances. Re-querying per refit is quadratic and makes multi-season runs
    # impractical; the slice below is exactly what a query with before=<date>
    # would have returned, because events are walked in date order.
    history = sorted(collect_observations(league), key=lambda match: match.date)
    consumed = 0

    model: ModelFit | None = None
    since_refit = 0

    # Elo advances incrementally alongside the replay, so its ratings are always
    # exactly the ratings a forecaster would have held before this match. Its
    # outcome mapping refits on the same cadence as Dixon-Coles, warm-started from
    # the previous fit because the parameters barely move between refits.
    elo_ratings = elo.EloRatings(config=elo_config or elo.EloConfig())
    elo_consumed = 0
    elo_outcome: elo.OutcomeModel | None = None

    # ClubElo needs no state of its own: the ratings arrive on each event, already
    # as they stood before kick-off. Samples accumulate as the replay walks
    # forward, so a fit never sees the match it is about to forecast.
    club_elo_samples: list[tuple[float, str]] = []
    club_elo_model: club_elo.ClubEloModel | None = None

    for event in events:
        sides = _sided_competitors(event)
        if sides is None:
            continue
        home, away = sides
        home_goals, away_goals = home.score_int, away.score_int
        if home_goals is None or away_goals is None:
            continue

        while consumed < len(history) and history[consumed].date < event.date:
            consumed += 1
        while elo_consumed < consumed:
            elo_ratings.update(history[elo_consumed])
            elo_consumed += 1

        if model is None or since_refit >= refit_every:
            if consumed < MINIMUM_MATCHES:
                report.skipped_no_history += 1
                continue
            model = fit(
                history[:consumed], reference_date=event.date, half_life_days=half_life_days
            )
            try:
                elo_outcome = elo.fit_outcome_model(elo_ratings.samples, initial=elo_outcome)
            except elo.NotEnoughData:
                elo_outcome = None
            try:
                club_elo_model = club_elo.fit(club_elo_samples, initial=club_elo_model)
            except elo.NotEnoughData:
                club_elo_model = None
            report.refits += 1
            since_refit = 0
        since_refit += 1

        try:
            grid = score_grid(model, home.team_id, away.team_id)
        except NotEnoughData:
            report.skipped_unknown_team += 1
            continue

        club_elo_ratings = club_elo.ratings_of(event)
        model_markets = markets.summarise(grid)
        probabilities = markets.match_odds(grid)
        # Prices are read before the reliability gate: the market comparison covers
        # every scored match, while the gate governs only whether to bet.
        prices = _priced_selections(event.pk)

        report.forecasts.append(
            ForecastRecord(
                event_espn_id=event.espn_id,
                date=event.date,
                home=home.team.abbreviation,
                away=away.team.abbreviation,
                probabilities=probabilities,
                actual=outcome_of(home_goals, away_goals),
                home_goals=home_goals,
                away_goals=away_goals,
                market_probabilities=_market_probabilities(prices),
                closing_probabilities=_devigged(
                    _book_prices(prices, CLOSING_BENCHMARK_PROVIDERS, strict=True)
                ),
                opening_prices=_book_prices(prices, MARKET_BENCHMARK_PROVIDERS),
                closing_prices=_book_prices(prices, CLOSING_BENCHMARK_PROVIDERS, strict=True),
                elo_probabilities=(
                    elo_outcome.probabilities(
                        elo_ratings.scaled_difference(home.team_id, away.team_id)
                    )
                    if elo_outcome is not None
                    else None
                ),
                club_elo_probabilities=(
                    club_elo_model.probabilities(*club_elo_ratings)
                    if club_elo_model is not None and club_elo_ratings is not None
                    else None
                ),
            )
        )

        # Recorded only after the forecast, so the match never trains the fit
        # that predicted it.
        sample = club_elo.sample_of(event, outcome_of(home_goals, away_goals))
        if sample is not None:
            club_elo_samples.append(sample)

        if model.effective_matches < min_effective_matches:
            report.skipped_unreliable_fit += 1
            continue

        if not prices:
            continue
        report.events_with_odds += 1

        for bet in find_value_bets(
            model_markets,
            prices,
            edge_threshold=edge_threshold,
            kelly_multiplier=kelly_multiplier,
            max_stake_fraction=max_stake_fraction,
        ):
            won = settle(bet.market, bet.selection, bet.line, home_goals, away_goals)
            if won is None:
                continue
            report.ledger.record(bet.stake_fraction, bet.decimal_odds, won)

    return report


def sweep_half_life(
    league: League,
    half_lives: list[float],
    *,
    refit_every: int = 5,
    date_from: datetime | None = None,
    date_to: datetime | None = None,
) -> list[dict]:
    """Score the model at several decay half-lives and rank them.

    The half-life decides how fast old matches stop counting, and guessing it is
    guessing how quickly the league turns over. This runs the same walk-forward
    backtest at each candidate and ranks by out-of-sample log-loss, so the value
    comes from the league's own history.

    Every run scores the same matches, so the numbers are directly comparable.
    Beware of reading too much into small gaps: with a few hundred matches the
    difference between neighbouring half-lives is often noise, which is why the
    spread across all candidates is reported alongside the winner.
    """
    results = []
    for half_life in half_lives:
        report = run(
            league,
            half_life_days=half_life,
            refit_every=refit_every,
            date_from=date_from,
            date_to=date_to,
        )
        scores = _scores(report.forecasts)
        results.append(
            {
                "half_life_days": half_life,
                "forecasts": len(report.forecasts),
                "log_loss": scores["log_loss"],
                "brier": scores["brier"],
                "accuracy": _accuracy(report.forecasts),
                "baseline_log_loss": _baseline_scores(report.forecasts)["log_loss"],
            }
        )

    scored = [row for row in results if row["log_loss"] is not None]
    scored.sort(key=lambda row: row["log_loss"])
    return scored + [row for row in results if row["log_loss"] is None]
